### ISSUE TITLE
hashlib scrypt not working due to missing openssl 1.1+

### ISSUE THREAD

**Issue by beac0n** [bitnami/bitnami-docker-python#10]
**Description**

hashlib.scrypt should be available, but it is not.
Maybe because openssl 1.1+ is missing

**Steps to reproduce the issue:**

1. run the docker image
2. python3
3. import hashlib
4. hashlib.scrypt

**Describe the results you received:**
```
import hashlib
hashlib.scrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hashlib' has no attribute 'scrypt'
```

**Describe the results you expected:**

```
import hashlib
hashlib.scyrpt
<built-in function scrypt>
```

**Version**

- Output of `docker version`:

```                                                                                                                                                                                                                                                                       
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838
  Built:            Fri Nov 15 03:17:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.2.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 19.03.5-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.12-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.29GiB
 Name: beac0nnotebook
 ID: PWAC:UYJ2:UANV:UHWD:VQUU:APOJ:PZ2C:XAAS:YV2Z:UESK:THNV:NUGG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.1, build unknown
docker-py version: 4.1.0
CPython version: 3.8.1
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @beac0n.

This is weird, because I'm not able to reproduce your issue:

```
$ docker pull bitnami/python:latest
latest: Pulling from bitnami/python
3c9020349340: Already exists
534d12347698: Pull complete
a1bc0f217f16: Pull complete
2282c7202d1e: Pull complete
eaa74249f55b: Pull complete
ddd56cad1e0d: Pull complete
Digest: sha256:a78702d4820131db7245415c9342de5b5c9b844e395e1f91435dc9bc0be783f4
Status: Downloaded newer image for bitnami/python:latest
docker.io/bitnami/python:latest

$ docker run --rm -ti bitnami/python:latest bash
root@46f524c307bb:/app# python
Python 3.7.6 (default, Dec 19 2019, 10:10:01)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> hashlib.scrypt
<built-in function scrypt>
>>>
```

Which container are you using?

**Comment by beac0n** [comment]
```
> $ docker run --rm -ti bitnami/python:3.7-ol-7-prod /bin/bash
bash-4.2# python3
Python 3.7.6 (default, Dec 19 2019, 10:13:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> hashlib.scrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hashlib' has no attribute 'scrypt'
>>> 
```

As you can see from the logs, I'm using the image `3.7-ol-7-prod`

**Comment by alemorcuq** [comment]
Hi, @beac0n.

Apparently, `scrypt` requires OpenSSL 1.1+, which isn't available in Oracle Linux 7:

```
$ docker run --rm -ti bitnami/python:3.7-ol-7-prod bash
bash-4.2# grep hashlib.scrypt -C2 /opt/bitnami/python/lib/python3.7/hashlib.py

try:
    # OpenSSL's scrypt requires OpenSSL 1.1+
    from _hashlib import scrypt
except ImportError:
    pass
bash-4.2#
```

There's little we can do about this. I would suggest using the Debian container instead, would that work for you?

**Comment by beac0n** [comment]
> Apparently, hashlib.scrypt requires OpenSSL 1.1+, which isn't available in Oracle Linux 7:
I know, that's why I wrote it in the title and in the issue itself ;-).

> There's little we can do about this
You could compile openssl 1.1 and then compile python 3.7 with openssl 1.1.
I managed to compile openssl inside the container, but didn't follow this route any further.

> I would suggest using the Debian container instead, would that work for you?
I already switched to the alpine docker image which includes openssl1.1+

I thought that the old openssl version is a bug, since hashlib.scrypt is supported sine python 3.6 (see https://docs.python.org/3/library/hashlib.html#hashlib.scrypt) and therefore in my opinion hashlib.scrypt should work in the python 3.7 image.

**Comment by alemorcuq** [comment]
Thank you for your feedback, @beac0n! We contemplated building OpenSSL ourselves, but we decided to rely on the distributions providing these libraries instead of having to build and maintain the libraries ourselves.

As I said earlier, our Debian docker image includes OpenSSL 1.1, so if you end up deciding to use that one, don't hesitate to open a new ticket if you find any issues.

**Comment by beac0n** [comment]
Will do, thanks for the quick response :+1:
